### ISSUE TITLE
add encryption & compression support

### ISSUE THREAD

**Issue by nbari** [s3m/s3m#56]
in the config add options like:

```
---
hosts:
  test:
    endpoint: xxxx
    access_key: xxxx
    secret_key: xxx
    enc_key: <here define the key to be used for encryption>
    enc_type: chacha2020
    compress: y # <---- to compress after encrypting for now using zst
```

~check for environment vars  like:~

    S3M_ENC_KEY=
    S3M_COMPRESS=
(envs will create more confusion)

Need to compress before and then encrypt to get a better compression ratio
